services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: example
      POSTGRES_DB: notes_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080